edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
newline_style = "unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
