[package]
name = "serenity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc_proc = { path = "ipc-proc", version = "*" }

[lib]
crate-type = [ "lib", "cdylib" ]
